nelmio_cors:
  defaults:
    origin_regex: false
    allow_credentials: true
    allow_origin: ["*"]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
    allow_headers:
      [
        "Content-Type",
        "Authorization",
        "Allow-Credentials",
        "Access-Control-Allow-Credentials",
      ]
    max_age: 3600
  paths:
    "^/": ~
