security:
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    in_memory: { memory: ~ }
    database_users:
      entity: { class: App\Entity\User, property: usjEmail }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      pattern: ^/
      provider: database_users
      json_login:
        check_path: login
      logout:
        path: logout
        invalidate_session: true
      # activate different ways to authenticate
      # http_basic: true
      # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
      # form_login: true
      # https://symfony.com/doc/current/security/form_login_setup.html

  role_hierarchy:
    ROLE_COACH: ROLE_PARTICIPANT
    ROLE_MODERATOR: [ROLE_COACH, ROLE_PARTICIPANT]
  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used

  access_control:
    - { path: ^/user_profile, method: GET, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    # - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
    # - { path: ^/, roles: ROLE_PARTICIPANT }
    # - { path: ^/profile, roles: ROLE_USER }

  encoders:
    Symfony\Component\Security\Core\User\User:
      algorithm: bcrypt
      cost: 12
    App\Entity\User:
      algorithm: bcrypt
      cost: 12
